"""desc_10000

Revision ID: 272a6bc2eb7c
Revises: 3019d3c8fd0a
Create Date: 2024-04-09 10:13:15.467175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '272a6bc2eb7c'
down_revision = '3019d3c8fd0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advertisement', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(length=1000),
               type_=sa.Text(length=10000),
               existing_nullable=True)

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique', ['name'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('registration_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_date', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('advertisement', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.Text(length=10000),
               type_=sa.TEXT(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###
